language: node_js
node_js:
  - 14.17.6
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database beanBlogDB_test;' -U postgres
  - psql -c "CREATE USER postgres_test WITH PASSWORD 'dung10";" -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage
